### ISSUE TITLE
Add Android namespace support

### ISSUE THREAD

**Issue by kuhnroyal** [dariocavada/dchs_motion_sensors#2]
This is needed in order to use newer AGP versions.

**Comment by dariocavada** [comment]
Thank you for bringing up the need to add Android namespace support to ensure compatibility with newer versions of the Android Gradle Plugin (AGP). Your insight is very valuable to the project.

Would you be willing and able to submit a Pull Request with the necessary changes? 

Thanks again for your contribution!

**Comment by dariocavada** [comment]
- updated https://pub.dev/packages/dchs_motion_sensors
- updated https://pub.dev/packages/panorama_viewer (depend on dchs_motion_sensors)

**Comment by kuhnroyal** [comment]
Awesome thanks!
